---
- name: Add Grafana APT repository key
  apt_key:
    url: "{{ grafana_key_url }}"
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: "deb {{ grafana_repo_url }} stable main"
    state: present
    filename: grafana

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Start and Enable Grafana Service
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  become: yes
- name: Allow Grafana port 3000
  ufw:
    rule: allow
    port: 3000
    proto: tcp
- name: Deploy Grafana Configuration
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: restart grafana
